[workspace]
members = [
    "day1_1_numbers", "day1_1_enums", "day1_1_strings", "day1_1_immutability_and_refs",
    "day1_2_struct_declare",
    
    "day2_1_functions_clousures", 
    "day2_2_dependencies",

    "day3_1_modules_decl",

    "step1"
    #"step_final"
]