[package]
name = "rest_http_routes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#async runtime lib
tokio = { version = "1.12", features = ["full"] }

actix-web = "4.0.1"